sonar.projectKey=marzo245_visubuy
sonar.organization=marzo245

# Nombre y versión visibles en SonarCloud
sonar.projectName=VisuBuy
sonar.projectVersion=1.0

# Código fuente del cliente Flutter
sonar.sources=lib
sonar.sourceEncoding=UTF-8

# Exclusiones: artefactos de build, generados, plugins nativos, configs
sonar.exclusions=**/build/**,**/.dart_tool/**,**/*.g.dart,**/*.freezed.dart,**/firebase_options.dart,android/**,ios/**,web/**,test/**,**/generated/**

# Si más adelante agregas tests, descomenta:
# sonar.tests=test
# sonar.dart.lcov.reportPaths=coverage/lcov.info
